#!/usr/bin/env python3
"""Generate the bitmap font used by supabase/functions/invite to draw the
dynamic Open Graph image (1200x630) at runtime.

The edge function runs in Deno with no native image stack, so it needs a tiny
monochrome glyph table. This script rasterizes each glyph with PIL (the same
tooling that produced og.png), thresholds it to black/white, and emits a
TypeScript module of 8x8 fixed-width bitmasks (bit 7 = leftmost pixel).

Regenerate with:  python3 scripts/generate-og-font.py
"""
import os

from PIL import Image, ImageDraw, ImageFont

OUT = os.path.join(
    os.path.dirname(__file__),
    "..",
    "supabase",
    "functions",
    "invite",
    "font.ts",
)

# Every character the invite card can render. Keep it a plain str with no
# duplicates; the em dash (U+2014), middle dot (U+00B7) and ellipsis (U+2026)
# are used by the tagline/footer/name-truncation respectively.
CHARS = (
    " ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    "0123456789"
    "'’-. ,!?·—…"
    "éèêëàâçîïôùûüœ"
    "ÉÈÊËÀÂÇÎÏÔÙÛÜ"
)

CELL_W = 8
CELL_H = 8
BASELINE = 7  # bottom row index (descenders sit on it)


def font(size: int, bold: bool = True):
    candidates = []
    if bold:
        candidates += [
            "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
            "/System/Library/Fonts/Supplemental/HelveticaNeue.ttc",
        ]
    candidates += [
        "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/System/Library/Fonts/Supplemental/Helvetica.ttc",
    ]
    for c in candidates:
        if os.path.exists(c):
            try:
                return ImageFont.truetype(c, size)
            except Exception:
                continue
    return ImageFont.load_default()


def rasterize(ch: str) -> list:
    """Return 8 row bitmasks (bit 7 = left) for a single character."""
    empty = [0x00] * CELL_H
    if ch == " ":
        return empty

    f = font(48, bold=True)
    box = Image.new("L", (96, 96), 0)
    d = ImageDraw.Draw(box)
    d.text((48, 48), ch, fill=255, font=f, anchor="mm")
    bbox = box.getbbox()
    if bbox is None:
        return empty

    glyph = box.crop(bbox)
    w, h = glyph.size
    if w < 1 or h < 1:
        return empty

    # Fit into an 8-wide x 7-tall envelope (the bottom row is the baseline).
    scale = min(CELL_W / w, (BASELINE) / h)
    nw = max(1, int(w * scale))
    nh = max(1, int(h * scale))
    glyph = glyph.resize((nw, nh), Image.LANCZOS)
    glyph = glyph.point(lambda p: 255 if p >= 110 else 0)

    canvas = Image.new("L", (CELL_W, CELL_H), 0)
    x0 = (CELL_W - nw) // 2
    y0 = BASELINE - nh + 1
    canvas.paste(glyph, (x0, y0))

    rows = []
    for y in range(CELL_H):
        row = 0
        for x in range(CELL_W):
            if canvas.getpixel((x, y)) >= 128:
                row |= 0x80 >> x
        rows.append(row)
    return rows


def main() -> None:
    seen = set()
    entries = []
    for ch in CHARS:
        if ch in seen:
            continue
        seen.add(ch)
        rows = rasterize(ch)
        # A glyph must not render as fully empty (except the space) — that
        # would silently drop letters from a name.
        if ch != " ":
            assert any(rows), f"empty glyph for {ch!r}"
        entries.append((ch, rows))

    lines = [
        "// GENERATED by scripts/generate-og-font.py — do not edit by hand.",
        "// Fixed-width 8x8 monochrome glyphs. Each row is a bitmask where",
        "// bit 7 (0x80) is the leftmost pixel. Used by lib.ts to draw the",
        "// dynamic invite OG card in Deno (no native font stack available).",
        f"export const FONT_WIDTH = {CELL_W};",
        f"export const FONT_HEIGHT = {CELL_H};",
        "export const FONT: Record<string, number[]> = {",
    ]
    for ch, rows in entries:
        body = ", ".join(f"0x{r:02X}" for r in rows)
        esc = ch.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"    '{esc}': [{body}],")
    # A hollow rectangle so unknown glyphs are visible but never crash.
    lines.append("    '\\uFFFD': [0xFF, 0x81, 0x81, 0x81, 0x81, 0x81, 0x81, 0xFF],")
    lines.append("};")
    lines.append("export const FALLBACK_GLYPH: number[] = FONT['\\uFFFD'];")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fp:
        fp.write("\n".join(lines))
    print(f"wrote {OUT} ({len(entries)} glyphs)")


if __name__ == "__main__":
    main()
