// The two bundled notification chimes: the audio itself (generated by
// scripts/audio/generate_chimes.py), the platform wiring, and which sound each
// notification type carries in its push payload.
import fs from 'fs';
import os from 'os';
import path from 'path';
import { spawnSync } from 'child_process';
import { EVENT_REGISTRY, chimeFor, soundFieldFor } from '../supabase/functions/dispatch-notification/registry';

const ROOT = path.resolve(__dirname, '..');
const SOUNDS = path.join(ROOT, 'assets', 'sounds');
const NAMES = ['patron_chime', 'patron_chime_urgent'] as const;

function readWav(file: string) {
  const b = fs.readFileSync(file);
  expect(b.toString('ascii', 0, 4)).toBe('RIFF');
  expect(b.toString('ascii', 8, 12)).toBe('WAVE');
  const channels = b.readUInt16LE(22);
  const rate = b.readUInt32LE(24);
  const bits = b.readUInt16LE(34);
  let off = 12;
  while (b.toString('ascii', off, off + 4) !== 'data') off += 8 + b.readUInt32LE(off + 4);
  const len = b.readUInt32LE(off + 4);
  const samples = new Int16Array(len / 2);
  for (let i = 0; i < samples.length; i++) samples[i] = b.readInt16LE(off + 8 + i * 2);
  return { channels, rate, bits, samples, seconds: samples.length / rate };
}

describe('chime audio masters', () => {
  const wavs = Object.fromEntries(NAMES.map(n => [n, readWav(path.join(SOUNDS, `${n}.wav`))]));

  it.each(NAMES)('%s is 44.1 kHz 16-bit mono', n => {
    expect(wavs[n]).toMatchObject({ channels: 1, rate: 44100, bits: 16 });
  });

  it('default is ~1.15 s and urgent ~1.35 s — both under 1.5 s', () => {
    expect(wavs.patron_chime.seconds).toBeGreaterThan(1.1);
    expect(wavs.patron_chime.seconds).toBeLessThan(1.25);
    expect(wavs.patron_chime_urgent.seconds).toBeGreaterThan(1.3);
    expect(wavs.patron_chime_urgent.seconds).toBeLessThan(1.5);
    for (const n of NAMES) expect(wavs[n].seconds).toBeLessThan(1.5);
  });

  it.each(NAMES)('%s peaks below 0 dBFS (about -1 dBFS) with no clipping', n => {
    const peak = Math.max(...Array.from(wavs[n].samples, Math.abs)) / 32768;
    const dbfs = 20 * Math.log10(peak);
    expect(peak).toBeLessThan(1);
    expect(dbfs).toBeLessThan(0);
    expect(dbfs).toBeGreaterThan(-1.5);
  });

  it.each(NAMES)('%s fades to silence (last ms is inaudible, last sample 0) and starts from zero', n => {
    const s = wavs[n].samples;
    const peakOf = (ms: number) => Math.max(...Array.from(s.slice(s.length - Math.round(ms * 44.1)), Math.abs));
    expect(peakOf(1)).toBeLessThanOrEqual(8);    // ~ -72 dBFS
    expect(peakOf(5)).toBeLessThan(100);         // ~ -50 dBFS
    expect(peakOf(50)).toBeGreaterThan(peakOf(5)); // a ramp, not a cut
    expect(s[s.length - 1]).toBe(0);
    expect(s[0]).toBe(0);
  });

  it('every platform file exists for both chimes and is non-trivial', () => {
    for (const n of NAMES) {
      expect(fs.statSync(path.join(SOUNDS, 'ios', `${n}.caf`)).size).toBeGreaterThan(10_000);
      expect(fs.statSync(path.join(SOUNDS, 'android', `${n}.ogg`)).size).toBeGreaterThan(1_000);
    }
  });
});

describe('generator determinism', () => {
  const PY = process.env.CHIME_PYTHON || 'python3';
  const py = spawnSync(PY, ['-c', 'import numpy'], { encoding: 'utf8' });
  const hasNumpy = py.status === 0;
  (hasNumpy ? it : it.skip)('two runs produce byte-identical WAVs (needs python3 + numpy)', () => {
    const dirs = [0, 1].map(() => fs.mkdtempSync(path.join(os.tmpdir(), 'chimes-')));
    for (const d of dirs) {
      const r = spawnSync(PY, [path.join(ROOT, 'scripts/audio/generate_chimes.py'), '--wav-only', '--out', d], { encoding: 'utf8' });
      expect(r.status).toBe(0);
    }
    for (const n of NAMES) {
      const a = fs.readFileSync(path.join(dirs[0], `${n}.wav`));
      const b = fs.readFileSync(path.join(dirs[1], `${n}.wav`));
      expect(a.equals(b)).toBe(true);
    }
  });
});

describe('platform wiring', () => {
  const appJson = JSON.parse(fs.readFileSync(path.join(ROOT, 'app.json'), 'utf8'));
  it('the local sound plugin is registered', () => {
    expect(appJson.expo.plugins).toContain('./plugins/withPatronChimes');
  });
  it('chimes are NOT in the expo-notifications list (iOS .caf and Android .ogg must not both land in res/raw)', () => {
    const notif = appJson.expo.plugins.find((p: unknown) => Array.isArray(p) && p[0] === 'expo-notifications');
    expect(JSON.stringify(notif)).not.toMatch(/patron_chime/);
  });
  it('Android channels are created under the chime names with the .ogg files', () => {
    const src = fs.readFileSync(path.join(ROOT, 'src/components/NotificationSetup.tsx'), 'utf8');
    expect(src).toMatch(/setNotificationChannelAsync\('patron_chime'/);
    expect(src).toMatch(/sound: 'patron_chime\.ogg'/);
    expect(src).toMatch(/setNotificationChannelAsync\('patron_chime_urgent'/);
    expect(src).toMatch(/sound: 'patron_chime_urgent\.ogg'/);
  });
  it('dispatch-notification sends the chime channel + a per-platform sound and no longer the legacy files', () => {
    const src = fs.readFileSync(path.join(ROOT, 'supabase/functions/dispatch-notification/index.ts'), 'utf8');
    expect(src).toMatch(/chimeFor\(event_type, payload, eventDef\)/);
    expect(src).toMatch(/sound: soundFieldFor\(chime, platform\)/);
    expect(src).not.toMatch(/patron_(default|urgent)\.wav/);
  });
});

describe('which sound each notification carries', () => {
  const def = (t: string) => EVENT_REGISTRY[t];

  it('7-day reminder and nudges → patron_chime', () => {
    expect(chimeFor('debt_aging_reminder', { count_7d: 3, count_30d: 0 }, def('debt_aging_reminder'))).toBe('patron_chime');
    for (const t of ['activation_nudge_1', 'activation_nudge_2', 'second_action_reminder', 'revenue_milestone']) {
      expect(chimeFor(t, {}, def(t))).toBe('patron_chime');
    }
  });

  it('30-day reminder → patron_chime_urgent (even when 7-day debts ride along)', () => {
    expect(chimeFor('debt_aging_reminder', { count_30d: 1 }, def('debt_aging_reminder'))).toBe('patron_chime_urgent');
    expect(chimeFor('debt_aging_reminder', { count_7d: 4, count_30d: 2 }, def('debt_aging_reminder'))).toBe('patron_chime_urgent');
  });

  it('founder new-user alert → patron_chime_urgent', () => {
    expect(chimeFor('founder_new_user', {}, def('founder_new_user'))).toBe('patron_chime_urgent');
  });

  it('every other registered event follows its existing urgency flag', () => {
    const special = new Set(['founder_new_user', 'debt_aging_reminder']);
    for (const [t, d] of Object.entries(EVENT_REGISTRY)) {
      if (special.has(t)) continue;
      expect(chimeFor(t, {}, d)).toBe(d.urgent ? 'patron_chime_urgent' : 'patron_chime');
    }
  });

  it('the payload sound: iOS gets the .caf file name, Android defers to its channel', () => {
    expect(soundFieldFor('patron_chime', 'ios')).toBe('patron_chime.caf');
    expect(soundFieldFor('patron_chime_urgent', 'ios')).toBe('patron_chime_urgent.caf');
    expect(soundFieldFor('patron_chime', 'android')).toBe('default');
    expect(soundFieldFor('patron_chime_urgent', null)).toBe('default'); // unknown platform → OS default, never an error
  });
});
